services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/log:/var/log/nginx

  tasks:
    build: ./tasks
    container_name: tasks
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - CF_DNS_NAME=${CF_DNS_NAME}
      - CF_PROXIED=${CF_PROXIED:-false}
      - DDNS_INTERVAL_MIN=${DDNS_INTERVAL_MIN}
      - HELLO_INTERVAL_MIN=${HELLO_INTERVAL_MIN}

  lazydocker:
    # Lazydocker is TUI/interactive; run it on-demand.
    # docker compose run --rm -it lazydocker
    image: lazyteam/lazydocker:latest
    container_name: lazydocker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.config/lazydocker:/.config/jesseduffield/lazydocker
    tty: true
    stdin_open: true

networks:
  # docker network create edge-proxy
  edge-proxy:
    external: true
    name: edge-proxy
